web:
  container_name: jira-mg-wallet.hipay-pos-platform.com
  build: .
  dockerfile: ./bin/docker/php5-6/Dockerfile
  ports:
    - "8044:8044"
  env_file:
    - ./bin/conf/development/mage.env.sample
    - ./bin/conf/development/mysql.env.sample
  volumes:
    - ./src/app/code/local/HimediaPayments:/var/www/htdocs/app/code/local/HimediaPayments
    - ./src/app/design/frontend/base/default/template/HimediaPayments/hipay:/var/www/htdocs/app/design/frontend/base/default/template/HimediaPayments/hipay
    - ./src/app/design/adminhtml/default/default/template/HimediaPayments:/var/www/htdocs/app/design/adminhtml/default/default/template/HimediaPayments
    - ./src/skin/adminhtml/base/default/css/HimediaPayments:/var/www/htdocs/skin/adminhtml/base/default/css/HimediaPayments
    - ./web:/var/www/htdocs
    - ./log:/var/www/htdocs/var/log
mysql:
  ports:
    - "3307:3306"
  env_file:
    - ./bin/conf/development/mysql.env.sample
  volumes:
    - ./data/mysql:/var/lib/mysql

